---

##########   BEAN-counter configuration file   #########

####  File/folder locations  ####

# Directory to which output is written
output_folder: output

# File that maps the lane column in the sample table to the
# folder containing raw sequencing data for that lane.
lane_location_file: config_files/lane_locations.txt

# File that contains all sample information, including unique
# IDs, negative control status, the sequence of the index
# tag(s) each sample was labeled with and the sequencing lane
# from which the data came.
sample_table_file: sample_table/sample_table_filtered.txt

# Tab-delimited text file in
# $BARSEQ_PATH/data/gene_barcode_files/ that maps barcodes to
# strains and their identifiers. Must contain unique
# "Strain_ID" column.
gene_barcode_file: barcodes/barcodes_filtered.txt

# YAML-formatted file in
# $BARSEQ_PATH/data/amplicon_struct_files/ that defines the
# structure of the sequenced PCR amplicons. This is required
# for correctly parsing the sequencing data.
amplicon_struct_file: config_files/amplicon_struct.yaml



####  Basic parameters  ####

# Verbosity of messages printed to stdout. 0 is none, 1 is
# default (step-relevant announcements), 2 prints object
# inspection results, and 3 presents even deeper (and more
# cryptic) inspection results.
verbosity: 1

# Column in the sample information table that specifies how to
# partition the raw count data prior to scoring interactions.
# The user must manually add the values into this column that
# identify the different partitions.
sub_screen_column: 



####  Advanced parameters  ####

# Do not change unless you are comfortable doing so :-)
# Number of cores to use for processes spread across multiple
# cores. Defaults to the number of cores detected divided by
# 2. Can be specified as an integer number of cores (num_cores
# >= 1), as a fraction of the number of available cores (0 <
# num_cores < 1), or as "all" to run on all cores. Note that
# "all" may not have much or any speed boost over 0.5.
num_cores: 

# Remove conditions matching the "barcode-specific" pattern
# (positive interactions for barcodes beginning with one
# particular base) with correlation greater than that defined
# by "barcode_specific_template_correlation_cutoff".
remove_barcode_specific_conditions: True

# See "remove_barcode_specific_conditions".
barcode_specific_template_correlation_cutoff: 0.3

# Remove conditions associated with highly-self-correlating
# index tags (in control conditions) with correlation greater
# than that defined by "index_tag_correlation_cutoff".
# Intended for use with larger screens, as these are more
# likely to have coverage of multiple negative control
# conditions with the same index tag.
remove_correlated_index_tags: True

# See "remove_correlated_index_tags".
index_tag_correlation_cutoff: 0.4

# Number of substitution errors allowed in the common primer
# sequence.
common_primer_tolerance: 2

# Number of substitution errors allowed in the barcode
# sequence.
barcode_tolerance: 2

# Read count below which strains in control conditions are
# labeled as "not detected" and set to NA prior to calculation
# of the mean control profile.
control_detection_limit: 20

# Read count below which strains in non-control conditions are
# "not detected." All counts below this number are set to this
# number, which prevents NAs when log-transforming. Also
# applies to control conditions when their normalized profiles
# are being computed.
sample_detection_limit: 20

# For a strain to pass, the fraction of conditions with read
# counts >= "strain_pass_read_count" must be >=
# "strain_pass_fraction". This filtering step occurs AFTER
# removing strains/conditions with zero counts.
strain_pass_read_count: 20

# See "strain_pass_read_count".
strain_pass_fraction: 0.25

# For a condition to pass, the fraction of conditions with
# read counts >= "condition_pass_read_count" must be >=
# "condition_pass_fraction". This filtering step occurs AFTER
# removing strains/conditions with zero counts.
condition_pass_read_count: 20

# See "condition_pass_read_count".
condition_pass_fraction: 0.25

...
